import { pgTable, text, serial, timestamp, integer, index, unique } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { usersTable } from "./users";

export const messagesTable = pgTable(
  "messages",
  {
    id: serial("id").primaryKey(),
    /** UUID v4 generated by client — used for replay-attack detection */
    messageId: text("message_id"),
    senderId: integer("sender_id")
      .notNull()
      .references(() => usersTable.id),
    recipientId: integer("recipient_id")
      .notNull()
      .references(() => usersTable.id),
    ciphertextForRecipient: text("ciphertext_for_recipient").notNull(),
    ciphertextForSender: text("ciphertext_for_sender").notNull(),
    ivForRecipient: text("iv_for_recipient").notNull(),
    ivForSender: text("iv_for_sender").notNull(),
    /** Client-provided send timestamp — used for replay window checking */
    clientSentAt: timestamp("client_sent_at", { withTimezone: true }),
    /** Delivery lifecycle: sent → delivered → read */
    status: text("status").notNull().default("sent"),
    /** Soft delete: non-null means deleted */
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    /* Unique constraint to reject duplicate message IDs (replay protection) */
    unique("uq_message_id").on(t.messageId),
    /* Speed up per-conversation lookups */
    index("idx_messages_sender").on(t.senderId, t.createdAt),
    index("idx_messages_recipient").on(t.recipientId, t.createdAt),
  ],
);

export const insertMessageSchema = createInsertSchema(messagesTable).omit({
  id: true,
  createdAt: true,
  deletedAt: true,
  status: true,
});
export type InsertMessage = z.infer<typeof insertMessageSchema>;
export type Message = typeof messagesTable.$inferSelect;
